FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:0.11 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY dashboard/api/pyproject.toml dashboard/api/
COPY dashboard/auth/pyproject.toml dashboard/auth/
COPY mdrun-api/pyproject.toml mdrun-api/
COPY notebook/pyproject.toml notebook/

RUN uv sync --frozen --no-dev --package mdrun-api --no-install-project

COPY mdrun-api/ .

RUN mkdir -p /data
RUN chown -R 1000:1000 /data /app

USER 1000:1000

EXPOSE 5000

ENV APP_ENV=dev
ENV PATH="/app/.venv/bin:$PATH"

CMD ["python", "app.py"]
