FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /data
RUN chown -R 1000:1000 /data /app

USER 1000:1000

EXPOSE 5000

ENV APP_ENV=dev

CMD ["python", "app.py"]
