FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:0.11 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY . .

RUN mkdir -p /data
RUN chown -R 1000:1000 /data /app

USER 1000:1000

EXPOSE 5000

ENV APP_ENV=dev
ENV PATH="/app/.venv/bin:$PATH"

CMD ["python", "app.py"]
