devNamespace: krenek-ns
prodNamespace: gmxhub-ns

dashboard:
  hostname: mddash-ljocha.dyn.cloud.e-infra.cz
  user: ljocha
  password: SOMETHING_STRONG
  image: 
    name: cerit.io/ljocha/mddash
    tag: dev
  devel: true

data:
  size: 10Gi

notebook:
  image: quay.io/jupyter/base-notebook
