# Development environment configuration

# Kubernetes namespace
namespace: krasa-ns

# Rancher project ID for user namespace annotation
rancherProjectId: "c-m-qvndqhf6:p-8rjpv"

# Global storage class for all persistent volumes
storageClassName: nfs-csi

# Container and helm chart registry
registry: cerit.io/xkrasa

# Dashboard hostname
dashboard:
  hostname: mddash-dev.dyn.cloud.e-infra.cz

# MDRepo integration for publishing experiments
mdrepo:
  url: https://workflow-repo.test.du.cesnet.cz
  scopes: user:email

# Notebook image (spawned by Dashboard pod)
notebook:
  image: cerit.io/xkrasa/mddash-notebook
  platform: linux/amd64
  tag: dev

# Sidecar container images for user pod
sidecars:
  platform: linux/amd64
  tag: dev
  pullPolicy: Always
  ui:
    image: cerit.io/xkrasa/mddash-ui
  proxy:
    image: cerit.io/xkrasa/mddash-proxy
  auth:
    image: cerit.io/xkrasa/mddash-auth
  api:
    image: cerit.io/xkrasa/mddash-api
  s3sync:
    image: cerit.io/xkrasa/mddash-s3sync

# S3 object storage configuration
s3:
  endpoint: https://s3.cl4.du.cesnet.cz

resources:
  singleuser:
    memory:
      guarantee: 512M
      limit: 4G
    cpu:
      guarantee: 0.2
      limit: 1
  namespaceQuota:
    requestsCpu: "2000m"
    requestsMemory: "4Gi"
    limitsCpu: "8000m"
    limitsMemory: "16Gi"
  pvcStorageSize: 10Gi

helm:
  package: mddash-dev

# mdrun-api service
mdrunApi:
  image: cerit.io/xkrasa/mdrun-api
  platform: linux/amd64
  tag: dev
  storage:  # Persistent storage for mdrun-api database
    size: 2Gi

# Gromacs Tuner service
gromacsTuner:
  image:
    repository: cerit.io/xkrasa/gromacs-tuner-api
    tag: "latest"
    pullPolicy: Always
  storage:
    size: 10Gi
  api:
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"
  ray:
    image: "cerit.io/adamondrejka/gmx-cuda-ray-2-42-1-with-user"
    head:
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "200m"
          memory: "512Mi"
    worker:
      maxReplicas: 1
      gpuProduct: "NVIDIA-A40"
      resources:
        limits:
          cpu: "4"
          memory: "16Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "4"  # should to be same as limit
          memory: "8Gi"
          nvidia.com/gpu: "1"
