apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-hub-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: hub
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-hub-clusterrole
  apiGroup: rbac.authorization.k8s.io
