ARG IMAGE=cerit.io/ljocha/mddash

FROM ${IMAGE}

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    bash \
    vim \
    git \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

# RUN rm -rf /opt/api

# assumes volume with API mounted on /home/jovyan
# RUN ln -s /home/jovyan/mddash/dashboard/api /opt

# RUN chown -R jovyan /opt/mddash

USER 1000
