ARG IMAGE=cerit.io/ljocha/mddash

FROM ${IMAGE}

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    bash \
    vim \
    git \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

USER 1000
