apiVersion: v1
kind: PersistentVolumeClaim
metadata:                                                                       
  name: mddash-home
spec:                                                                           
  accessModes:                                                                  
    - ReadWriteMany                                                             
  resources:                                                                    
    requests:                                                                   
      storage: 5Gi
  storageClassName: standard
