import React, { useEffect, useMemo, useState } from "react"

import { useQueryClient } from "@tanstack/react-query"
import { Atom, BarChart2, Play, SlidersHorizontal, Upload } from "lucide-react"

import { cn } from "@/lib/utils"
import { DEBUG } from "@/util/const"
import { type Experiment, type Simulation } from "@/util/types"
import { useExperimentStep } from "@/hooks/use-experiment"
import { useSimulations } from "@/hooks/use-simulations"
import { Button } from "@/components/ui/button"

import AnalyzeStep from "./AnalyzeStep"
import PublishStep from "./PublishStep"
import RunStep from "./RunStep"
import WizardSetup from "./SetupStep"
import SimulationTabs from "./SimulationTabs"
import TuneStep from "./TuneStep"

const STEP_ICONS = [Atom, SlidersHorizontal, Play, BarChart2, Upload]
const STEP_LABELS = ["Setup", "Tune", "Run", "Analyze", "Publish"]
const STEP_COMPONENTS = [WizardSetup, TuneStep, RunStep, AnalyzeStep, PublishStep]
const ANALYZE_STEP = STEP_LABELS.indexOf("Analyze")

export interface WizardStepperProps {
  experiment: Experiment
}

export interface WizardStepProps {
  experiment: Experiment
  nextStep: () => void
  changeStep: (step: number) => void
  simulations: Simulation[]
  simulationsLoading: boolean
  selectedSimulation: Simulation | null
  selectedSimulationPath: string | null
  setSelectedSimulationPath: (simulationPath: string | null) => void
}

const WizardStepper = ({ experiment }: WizardStepperProps) => {
  const queryClient = useQueryClient()
  const [activeStep, setActiveStep] = useState(Math.min(experiment.step, STEP_LABELS.length - 1))
  const [selectedSimulationPath, setSelectedSimulationPath] = useState<string | null | undefined>(undefined)

  const { data: simulations = [], isLoading: simulationsLoading } = useSimulations(experiment.id)
  const selectedSimulation = useMemo(
    () => simulations.find((simulation) => simulation.simulation_path === selectedSimulationPath) ?? null,
    [selectedSimulationPath, simulations]
  )

  // Poll experiment step; hook updates experiment cache when step changes
  useExperimentStep(experiment.id, experiment.step)

  useEffect(() => {
    if (selectedSimulationPath !== undefined || simulationsLoading) return
    setSelectedSimulationPath(simulations[0]?.simulation_path ?? null)
  }, [selectedSimulationPath, simulationsLoading, simulations])

  // Re-check simulation file existence when entering the analyze step. Output
  // files (e.g. trajectory) may have been generated by a running/finished job
  // since the list was last fetched, and the backend resolves existence on read.
  useEffect(() => {
    if (activeStep === ANALYZE_STEP) {
      queryClient.invalidateQueries({ queryKey: ["experiment", experiment.id, "simulations"] })
    }
  }, [activeStep, experiment.id, queryClient])

  const changeStep = (step: number) => {
    if (step < 0 || step >= STEP_LABELS.length) return
    if (step > experiment.step) return // can only go forward using nextStep
    setActiveStep(step)
  }

  const nextStep = () => {
    if (experiment.step >= STEP_LABELS.length - 1) return
    const newStep = experiment.step + 1
    setActiveStep(newStep)
    queryClient.setQueryData<Experiment>(["experiment", experiment.id], (old) =>
      old ? { ...old, step: newStep } : old
    )
  }

  const selectSimulation = (simulationPath: string | null) => {
    setSelectedSimulationPath(simulationPath)
  }

  const createSimulation = () => {
    setSelectedSimulationPath(null)
    changeStep(0)
  }

  const ActiveComponent = STEP_COMPONENTS[activeStep]

  return (
    <div className="flex w-full flex-col">
      <div className="flex flex-col gap-5 px-6 pt-6 pb-5">
        {DEBUG && (
          <Button variant="default" onClick={nextStep}>
            DEBUG: next step
          </Button>
        )}

        <div className="flex items-center justify-center">
          {STEP_LABELS.map((label, idx) => {
            const Icon = STEP_ICONS[idx]
            const isCompleted = idx < experiment.step || idx < activeStep
            const isActive = idx === activeStep
            const isClickable = idx <= experiment.step

            return (
              <React.Fragment key={label}>
                <div className="flex flex-col items-center gap-1">
                  <button
                    type="button"
                    disabled={!isClickable}
                    onClick={() => changeStep(idx)}
                    className={cn(
                      "flex h-12 w-12 items-center justify-center rounded-full border-2 text-white transition-all",
                      isActive && "bg-primary border-primary scale-110 shadow-md",
                      isCompleted && !isActive && "border-green-500 bg-green-500",
                      !isActive && !isCompleted && "bg-muted border-border text-muted-foreground",
                      isClickable && !isActive && !isCompleted && "cursor-pointer hover:scale-105 hover:shadow",
                      isClickable && isCompleted && "cursor-pointer hover:scale-105"
                    )}
                  >
                    <Icon className="h-5 w-5" />
                  </button>
                  <span className={cn("text-xs font-medium", isActive ? "text-primary" : "text-muted-foreground")}>
                    {label}
                  </span>
                </div>

                {idx < STEP_LABELS.length - 1 && (
                  <div
                    className={cn(
                      "mx-1 mb-5 h-0.5 flex-1 transition-colors",
                      idx < activeStep || idx < experiment.step
                        ? "bg-green-500"
                        : idx === activeStep
                          ? "bg-primary"
                          : "bg-border"
                    )}
                  />
                )}
              </React.Fragment>
            )
          })}
        </div>
      </div>

      <div className="border-border border-y py-2">
        <SimulationTabs
          simulations={simulations}
          selectedPath={selectedSimulationPath ?? null}
          loading={simulationsLoading}
          onSelect={selectSimulation}
          onCreate={createSimulation}
        />
      </div>

      <div className="px-6 pt-5 pb-6">
        <ActiveComponent
          experiment={experiment}
          nextStep={nextStep}
          changeStep={changeStep}
          simulations={simulations}
          simulationsLoading={simulationsLoading}
          selectedSimulation={selectedSimulation}
          selectedSimulationPath={selectedSimulationPath ?? null}
          setSelectedSimulationPath={selectSimulation}
        />
      </div>
    </div>
  )
}

export default WizardStepper
