import React, { useEffect } from "react"

import { useQueryClient } from "@tanstack/react-query"
import { useNavigate, useSearch } from "@tanstack/react-router"
import { Atom, BarChart2, Play, SlidersHorizontal, Upload } from "lucide-react"

import { cn } from "@/lib/utils"
import { DEBUG } from "@/util/const"
import { type Experiment, type Simulation } from "@/util/types"
import { useSimulations } from "@/hooks/use-simulations"
import { Button } from "@/components/ui/button"

import AnalyzeStep from "./AnalyzeStep"
import PublishStep from "./PublishStep"
import RunStep from "./RunStep"
import WizardSetup from "./SetupStep"
import SimulationTabs from "./SimulationTabs"
import TuneStep from "./TuneStep"

const STEP_ICONS = [Atom, SlidersHorizontal, Play, BarChart2, Upload]
const STEP_LABELS = ["Setup", "Tune", "Run", "Analyze", "Publish"]
const STEP_COMPONENTS = [WizardSetup, TuneStep, RunStep, AnalyzeStep, PublishStep]
const SETUP_STEP = 0
const ANALYZE_STEP = STEP_LABELS.indexOf("Analyze")
const PUBLISH_STEP = STEP_LABELS.indexOf("Publish")
const NEW_TAB = "_new"
const SIMULATIONS_POLL_MS = 5000

export interface WizardStepperProps {
  experiment: Experiment
}

export interface WizardStepProps {
  experiment: Experiment
  /** The selected setup; null ⇔ create mode (`?tab=_new`). */
  simulation: Simulation | null
  goToStep: (step: number) => void
}

interface ResolvedWizard {
  tab: string
  step: number
  simulation: Simulation | null
  createMode: boolean
  maxStep: number
}

/** Furthest step reachable for a tab: its own ladder, plus the experiment-wide Publish gate. */
function maxAllowedStep(simulation: Simulation | null, createMode: boolean, experiment: Experiment): number {
  if (createMode) return SETUP_STEP
  const setupStep = simulation?.step ?? SETUP_STEP
  return experiment.step >= PUBLISH_STEP ? Math.max(setupStep, PUBLISH_STEP) : setupStep
}

/** Resolve raw URL state to the canonical tab/step the wizard should show. */
function resolveWizard(
  search: { tab?: string; step?: number },
  simulations: Simulation[],
  experiment: Experiment
): ResolvedWizard {
  let simulation: Simulation | null = null
  let tab = search.tab

  if (search.tab === NEW_TAB) {
    tab = NEW_TAB
  } else {
    simulation = simulations.find((s) => s.name === search.tab) ?? simulations[0] ?? null
    tab = simulation?.name ?? NEW_TAB
  }

  const createMode = tab === NEW_TAB
  const maxStep = maxAllowedStep(simulation, createMode, experiment)
  // Honor a pinned step within structural bounds — forward bumps (e.g. Tune → Run
  // right after job launch) must stick even while the polls are still catching up.
  // Button gating against maxStep is what prevents accidental skipping; step-level
  // guards handle content for steps the setup has not reached yet.
  const step = Math.min(Math.max(search.step ?? simulation?.step ?? SETUP_STEP, SETUP_STEP), PUBLISH_STEP)

  return { tab, step, simulation, createMode, maxStep }
}

const WizardStepper = ({ experiment }: WizardStepperProps) => {
  const queryClient = useQueryClient()
  const search = useSearch({ from: "/$id/wizard" })
  const navigate = useNavigate({ from: "/$id/wizard" })
  const { data: simulations = [], isLoading: simulationsLoading } = useSimulations(experiment.id, {
    refetchInterval: SIMULATIONS_POLL_MS,
  })

  const resolved = simulationsLoading ? null : resolveWizard(search, simulations, experiment)

  const goToStep = (step: number) => navigate({ search: (prev) => ({ ...prev, step }) })

  // Canonicalize the URL: missing/unknown tab falls back to the first setup (or
  // create mode when none exists), and missing/out-of-bounds steps default to
  // the setup's own step. Pinned steps within bounds are honored (see
  // resolveWizard) — gating lives in the stepper buttons, not the URL.
  useEffect(() => {
    if (!resolved) return
    if (resolved.tab !== search.tab || resolved.step !== search.step) {
      navigate({ search: { tab: resolved.tab, step: resolved.step }, replace: true })
    }
  }, [resolved, search.tab, search.step, navigate])

  // Re-check simulation file existence when entering the analyze step. Output
  // files (e.g. trajectory) may have been generated by a running/finished job
  // since the list was last fetched, and the backend resolves existence on read.
  useEffect(() => {
    if (resolved?.step === ANALYZE_STEP) {
      queryClient.invalidateQueries({ queryKey: ["experiment", experiment.id, "simulations"] })
    }
  }, [resolved?.step, experiment.id, queryClient])

  const selectSimulation = (name: string) => {
    const sim = simulations.find((s) => s.name === name)
    navigate({ search: { tab: name, step: sim?.step ?? SETUP_STEP } })
  }

  const createSimulation = () => navigate({ search: { tab: NEW_TAB, step: SETUP_STEP } })

  const progress = resolved && !resolved.createMode ? Math.max(resolved.step, resolved.maxStep) : (resolved?.step ?? 0)
  const ActiveComponent = resolved ? STEP_COMPONENTS[resolved.step] : null

  return (
    <div className="flex w-full flex-col">
      <div className="border-border border-b px-4 pt-4 pb-2">
        <SimulationTabs
          simulations={simulations}
          selectedName={resolved && !resolved.createMode ? resolved.tab : null}
          loading={simulationsLoading}
          onSelect={selectSimulation}
          onCreate={createSimulation}
        />
      </div>

      <div className="flex flex-col gap-5 px-6 pt-6 pb-5">
        {DEBUG && resolved && (
          <Button variant="default" onClick={() => goToStep(Math.min(resolved.step + 1, PUBLISH_STEP))}>
            DEBUG: next step
          </Button>
        )}

        <div className="flex items-center justify-center">
          {STEP_LABELS.map((label, idx) => {
            const Icon = STEP_ICONS[idx]
            const isCompleted = resolved ? idx < progress : false
            const isActive = resolved ? idx === resolved.step : false
            const isClickable = DEBUG ? true : resolved ? idx <= resolved.maxStep : false

            return (
              <React.Fragment key={label}>
                <div className="flex flex-col items-center gap-1">
                  <button
                    type="button"
                    disabled={!isClickable}
                    onClick={() => goToStep(idx)}
                    className={cn(
                      "flex h-12 w-12 items-center justify-center rounded-full border-2 text-white transition-all",
                      isActive && "bg-primary border-primary scale-110 shadow-md",
                      isCompleted && !isActive && "border-green-500 bg-green-500",
                      !isActive && !isCompleted && "bg-muted border-border text-muted-foreground",
                      isClickable && !isActive && !isCompleted && "cursor-pointer hover:scale-105 hover:shadow",
                      isClickable && isCompleted && "cursor-pointer hover:scale-105"
                    )}
                  >
                    <Icon className="h-5 w-5" />
                  </button>
                  <span className={cn("text-xs font-medium", isActive ? "text-primary" : "text-muted-foreground")}>
                    {label}
                  </span>
                </div>

                {idx < STEP_LABELS.length - 1 && (
                  <div
                    className={cn(
                      "mx-1 mb-5 h-0.5 flex-1 transition-colors",
                      idx < progress ? "bg-green-500" : isActive ? "bg-primary" : "bg-border"
                    )}
                  />
                )}
              </React.Fragment>
            )
          })}
        </div>
      </div>

      <div className="border-border border-t px-6 pt-5 pb-6">
        {resolved && ActiveComponent ? (
          <ActiveComponent experiment={experiment} simulation={resolved.simulation} goToStep={goToStep} />
        ) : null}
      </div>
    </div>
  )
}

export default WizardStepper
