apiVersion: v1
kind: Service
metadata:
  name: tuner-api-svc
  labels:
    app.kubernetes.io/name: tuner
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/name: tuner
    app.kubernetes.io/component: api
