apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tuner-ray
  labels:
    app.kubernetes.io/name: tuner
    app.kubernetes.io/component: ray
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - ray-head
          - ray-worker
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: tuner
