apiVersion: v2
name: mddash-jupyterhub
description: A Helm chart for JupyterHub with MDDash
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: jupyterhub
    version: "4.4.0"
    repository: "https://hub.jupyter.org/helm-chart/"
  - name: mdrun-api
    version: "0.1.0"
    repository: "file://../mdrun-api"
  - name: tuner
    version: "0.1.0"
    repository: "file://../tuner"
