apiVersion: v2
name: mddash-jupyterhub
description: A Helm chart for JupyterHub with MDDash
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: jupyterhub
    version: "4.2.0"
    repository: "https://hub.jupyter.org/helm-chart/"
  - name: mdrun-api
    version: "0.1.0"
    repository: "oci://cerit.io/xkrasa"
  - name: gromacs-tuner
    version: "0.1.2"
    repository: "oci://cerit.io/xkrasa"
