apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdrun-api-data
  labels:
    app: mdrun-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
